export const gameConfig = {
  grid: {
    cols: 8,
    rows: 8,
    tileSize: 1.0,
    tileGap: 0.04,
    tileHeight: 0.12,
  },
  camera: {
    frustumSize: 14,
    elevation: 60,
    azimuth: 45,
    near: 0.1,
    far: 100,
  },
  movement: {
    animationDuration: 0.35,
    hopHeight: 0.3,
  },
  vfx: {
    idleBobSpeed:       1.8,
    idleBobAmplitude:   0.04,
    slashRingSpeed:     2.2,
    p1LightColor:       0x60a5fa,
    p1LightIntensity:   3.5,
    p1LightDistance:    3.5,
    p2LightColor:       0xd946ef,
    p2LightIntensity:   3.5,
    p2LightDistance:    3.5,
    bloomStrength:      0.4,
    bloomRadius:        0.3,
    bloomThreshold:     0.35,
  },
  scene: {
    background:         0x030712,
    fogColor:           0x030712,
    fogNear:            14,
    fogFar:             32,
    ambientIntensity:   0.35,
    dirLightIntensity:  1.1,
  },
} as const;
